CREATE TABLE IF NOT EXISTS `todos` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `desc` TEXT NOT NULL,
    `is_completed` TINYINT(1) DEFAULT 0,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 AUTO_INCREMENT=101 COLLATE=utf8mb4_unicode_ci;
