CREATE TABLE IF NOT EXISTS `todos` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `desc` TEXT NOT NULL,
    `is_completed` TINYINT(1),
    PRIMARY KEY (`id`)
)ENGINE=InnoDB CHARSET=UTF8MB4 AUTO_INCREMENT=101;
